version: '3.9'

services:
    # FigureItOut Database
    mongo_database:
        image: mongo:4.4.4
        ports: 
            - "3314:27019"
        restart: always
        volumes:
            - db_volume_mongo_database:/FigureItOut/database
            - ../database/FigureDB.js:/docker-entrypoint-initdb.d/FigureDB.js:ro
        command: mongod --auth
        environment:
            MONGO_INITDB_DATABASE: FigureDB
            MONGO_INITDB_ROOT_USERNAME: figureAdmin
            MONGO_INITDB_ROOT_PASSWORD: proyectoweb
        container_name: db_figureitout
    #Api
    api_figureitout:
        image: api
        depends_on: 
            - "mongo_database"
        ports:
            - "4000:4000"
        build: 
            context: ../api/
            dockerfile: Dockerfile
         environment: 
            DB_CONNECTION_STRING: "mongodb://figureAdmin:proyectoweb@mongo_database"
volumes:
    db_volume_mongo_database:
